### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by sandman4sure** [marstonstudio/yacprojects#1]
When you remove an entry from YacReader Library and run the batch again you will get an error:

```
SELECT ci.id, c.path, ci.volume, ci.number 
                FROM comic_info AS ci 
                JOIN comic AS c ON c.comicInfoId = ci.id 
                WHERE ci.id = 704;
Traceback (most recent call last):
  File "./yacxmlupdater.py", line 231, in <module>
    updater.main()
  File "./yacxmlupdater.py", line 54, in main
    comic_record = ComicRecord(comic_row[0], comic_row[1], comic_row[2], comic_row[3])
TypeError: 'NoneType' object is not subscriptable
```

This query will give zero results back

**Comment by sandman4sure** [comment]
P.S quick fix for me to get it working again added to line 54:

```
if not comic_row:
            	self.logger.info("Skipping because query didn't give results, probably because of removed items")
            	id_current += 1
            	continue
```

**Comment by marstonstudio** [comment]
@sandman4sure : thanks! any interest in submitting as a pull request?

**Comment by sandman4sure** [comment]
@marstonstudio I don't know if this is the cleanest solution as I'm not really a python programmer.
But if you think it is ok I can create a PR

**Comment by marstonstudio** [comment]
This looks good to me!

**Comment by sandman4sure** [comment]
https://github.com/marstonstudio/yacprojects/pull/2

**Comment by marstonstudio** [comment]
PR merged, thanks for contributing!
